import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import styles from '../styles/Home.module.css'
import { NavbarContainer } from './components/Navbar/Navbar.container'

export default function Home() {
  const mode = useSelector(state => state.screenModeReducer)
  return (<>
  <NavbarContainer/>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          {mode.bool?'light':'dark'}
        </h1>   
      </main>
    </div>
    </>
  )
}
